export interface BackupVolume {
  volumeName: any;
  serviceStatus: any;
  creationDate: any;
  suspendDate: any;
  suspendType: any;
  vpcName: any;
  customerEmail: any;
  backupPackgeName: any;
  name: any;
  size: any;
  description: any;
  volumeId: any;
  cloudId: any;
  regionId: any;
  customerId: any;
  scheduleId: any;
  instanceBackupId: any;
  isBootable: any;
  iops: any;
  offerId: any;
  cloudIdentity: any;
  projectName: any;
  projectId: any;
  backupPackageId: any;
  status: any;
  id: any;
  expirationDate: any;
}
